Job "fetch_and_send_data (trigger: interval[0:30:00], next run at: 2025-03-08 08:01:54 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/api_consumer.py", line 26, in fetch_and_send_data
    exchange_info = raw_data["Realtime Currency Exchange Rate"]
KeyError: 'Realtime Currency Exchange Rate'
Job "fetch_and_send_data (trigger: interval[0:30:00], next run at: 2025-03-08 08:05:25 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/api_consumer.py", line 26, in fetch_and_send_data
    exchange_info = raw_data["Realtime Currency Exchange Rate"]
KeyError: 'Realtime Currency Exchange Rate'
Job "fetch_and_send_data (trigger: interval[0:30:00], next run at: 2025-03-08 08:31:54 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/api_consumer.py", line 26, in fetch_and_send_data
    exchange_info = raw_data["Realtime Currency Exchange Rate"]
KeyError: 'Realtime Currency Exchange Rate'
Job "fetch_and_send_data (trigger: interval[0:30:00], next run at: 2025-03-08 08:35:25 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/api_consumer.py", line 26, in fetch_and_send_data
    exchange_info = raw_data["Realtime Currency Exchange Rate"]
KeyError: 'Realtime Currency Exchange Rate'
Job "fetch_and_send_data (trigger: interval[0:30:00], next run at: 2025-03-08 09:01:54 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/api_consumer.py", line 26, in fetch_and_send_data
    exchange_info = raw_data["Realtime Currency Exchange Rate"]
KeyError: 'Realtime Currency Exchange Rate'
Job "fetch_and_send_data (trigger: interval[0:30:00], next run at: 2025-03-08 09:05:25 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/api_consumer.py", line 26, in fetch_and_send_data
    exchange_info = raw_data["Realtime Currency Exchange Rate"]
KeyError: 'Realtime Currency Exchange Rate'
Job "fetch_and_send_data (trigger: interval[0:30:00], next run at: 2025-03-08 09:31:54 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/api_consumer.py", line 26, in fetch_and_send_data
    exchange_info = raw_data["Realtime Currency Exchange Rate"]
KeyError: 'Realtime Currency Exchange Rate'
Job "fetch_and_send_data (trigger: interval[0:30:00], next run at: 2025-03-08 09:35:25 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/api_consumer.py", line 26, in fetch_and_send_data
    exchange_info = raw_data["Realtime Currency Exchange Rate"]
KeyError: 'Realtime Currency Exchange Rate'
Job "fetch_and_send_data (trigger: interval[0:30:00], next run at: 2025-03-08 10:01:54 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/api_consumer.py", line 26, in fetch_and_send_data
    exchange_info = raw_data["Realtime Currency Exchange Rate"]
KeyError: 'Realtime Currency Exchange Rate'
Job "fetch_and_send_data (trigger: interval[0:30:00], next run at: 2025-03-08 10:05:25 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/api_consumer.py", line 26, in fetch_and_send_data
    exchange_info = raw_data["Realtime Currency Exchange Rate"]
KeyError: 'Realtime Currency Exchange Rate'
Sent to Kafka: {'timestamp': '2025-03-08 12:32:03', 'from_currency': 'BTC', 'to_currency': 'USD', 'exchange_rate': 86153.43, 'bid_price': 86150.328, 'ask_price': 86153.546}
Sent to Kafka: {'timestamp': '2025-03-08 12:32:03', 'from_currency': 'BTC', 'to_currency': 'EUR', 'exchange_rate': 79642.73, 'bid_price': 79640.456, 'ask_price': 79643.426}
Sent to Kafka: {'timestamp': '2025-03-08 12:32:01', 'from_currency': 'ETH', 'to_currency': 'USD', 'exchange_rate': 2160.72, 'bid_price': 2160.615, 'ask_price': 2160.759}
Sent to Kafka: {'timestamp': '2025-03-08 12:32:05', 'from_currency': 'ETH', 'to_currency': 'EUR', 'exchange_rate': 1996.03, 'bid_price': 1995.93, 'ask_price': 1996.059}
Sent to Kafka: {'timestamp': '2025-03-08 12:32:05', 'from_currency': 'XRP', 'to_currency': 'USD', 'exchange_rate': 2.3313, 'bid_price': 2.33127, 'ask_price': 2.33134}
Sent to Kafka: {'timestamp': '2025-03-08 12:32:05', 'from_currency': 'XRP', 'to_currency': 'EUR', 'exchange_rate': 2.1521, 'bid_price': 2.15203, 'ask_price': 2.15219}
Crypto data streaming started... Running every 30 mins
Traceback (most recent call last):
  File "/home/ubuntu/api_consumer.py", line 46, in <module>
    scheduler.start()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/schedulers/blocking.py", line 19, in start
    self._main_loop()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/schedulers/blocking.py", line 28, in _main_loop
    self._event.wait(wait_seconds)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
Listening for messages
Traceback (most recent call last):
  File "/home/ubuntu/consumer.py", line 19, in <module>
    session = cluster.connect('crypto')
  File "cassandra/cluster.py", line 1717, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1753, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1740, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3543, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3588, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
Sent to Kafka: {'timestamp': '2025-03-08 12:33:03', 'from_currency': 'BTC', 'to_currency': 'USD', 'exchange_rate': 86153.43, 'bid_price': 86149.389, 'ask_price': 86157.044}
Sent to Kafka: {'timestamp': '2025-03-08 12:33:31', 'from_currency': 'BTC', 'to_currency': 'EUR', 'exchange_rate': 79536.38, 'bid_price': 79533.87, 'ask_price': 79536.92}
Sent to Kafka: {'timestamp': '2025-03-08 12:33:01', 'from_currency': 'ETH', 'to_currency': 'USD', 'exchange_rate': 2160.72, 'bid_price': 2160.714, 'ask_price': 2160.81}
Sent to Kafka: {'timestamp': '2025-03-08 12:33:32', 'from_currency': 'ETH', 'to_currency': 'EUR', 'exchange_rate': 1996.03, 'bid_price': 1995.95, 'ask_price': 1996.129}
Sent to Kafka: {'timestamp': '2025-03-08 12:33:05', 'from_currency': 'XRP', 'to_currency': 'USD', 'exchange_rate': 2.3313, 'bid_price': 2.33129, 'ask_price': 2.3314}
Sent to Kafka: {'timestamp': '2025-03-08 12:33:33', 'from_currency': 'XRP', 'to_currency': 'EUR', 'exchange_rate': 2.1521, 'bid_price': 2.15209, 'ask_price': 2.1521}
Crypto data streaming started... Running every 30 mins
Traceback (most recent call last):
  File "/home/ubuntu/api_consumer.py", line 46, in <module>
    scheduler.start()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/schedulers/blocking.py", line 19, in start
    self._main_loop()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/apscheduler/schedulers/blocking.py", line 28, in _main_loop
    self._event.wait(wait_seconds)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
